name: unit tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Install Ubuntu dependencies
        run: sudo apt update && sudo apt-get -y install gettext appstream pkg-config libcairo2-dev gir1.2-gtk-3.0 libgirepository1.0-dev libicu-dev libopencv-dev python3-opencv python3-numpy tesseract-ocr tesseract-ocr-all gir1.2-pango-1.0 python3-gi-cairo
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install pycairo PyGObject pytest PyYAML jsonschema pyICU
          pip install git+https://github.com/gramps-project/gramps.git@maintenance/gramps52
          pip install -r requirements-dev.txt
          pip install .
          pip list
      - name: Test with pytest
        run: pytest
